#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jan 20, 2024 01:30:26 AM JST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import test

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = test.Toplevel1(_top1)
    root.mainloop()

def put_bottun1(*args):
    if _debug:
        print('test_support.put_bottun1')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def put_spin1(*args):
    print(_w1.Spinbox1.get())
    if _debug:
        print('test_support.put_spin1')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    test.start_up()




